### ISSUE TITLE
Switch to StaticJs CMS?

### ISSUE THREAD

**Issue by ptman** [itsmejoeeey/docker-decap-cms-standalone#1]
https://github.com/staticjscms

Static CMS is a fork of Netlify CMS focusing on the core product over adding massive, scope expanding, new features.

**Comment by itsmejoeeey** [comment]
Although Netlify CMS is currently unmaintained, I'm not convinced Static CMS is the right choice to use at this time either:

[This comment on the Netlify forums](https://answers.netlify.com/t/is-this-project-dead/70988/67) summarizes the situation well:

> I want to note - anyone considering using the staticccms fork should read this comment and the thread surrounding it: [Create NetlifyCMS to StaticCMS Migration Guide · Issue #46 · StaticJsCMS/static-cms · GitHub 25](https://github.com/StaticJsCMS/static-cms/issues/46#issuecomment-1291473172)
> 
> My two cents: the fork is a fantastic and commendable effort, but it’s a complete rewrite, removes a huge number of features, will never even attempt be kept in sync with the original, and most important of all - is made by a solo developer without many other OSS projects that I’m aware of, with no financial backing, for a church website. It would be a big risk for most teams to rely on it for a production use case.

I am not looking at supporting Static CMS at this time.

**Comment by itsmejoeeey** [comment]
Netlify CMS has new maintainers and is being rebranded to Decap CMS.

We hope the project will continue to prosper. This repo will update to match in #2.
