### ISSUE TITLE
Bitbucket Support ?

### ISSUE THREAD

**Issue by AnimeshRy** [itsmejoeeey/docker-decap-cms-standalone#5]
Hey are you planning to add bitbucket as an githost as well?

**Comment by itsmejoeeey** [comment]
This project just dockerizes a few projects so they can be used easily together. The external authentication is handled by the integration of `vencax/netlify-cms-github-oauth-provider`.

As noted in their `README.md`
> Github, Github Enterprise and Gitlab are currently supported, but as this is a general Oauth client, feel free to submit a PR to add other git hosting providers.

An issue already exists in their issue tracker for Bitbucket support. See here:
https://github.com/vencax/netlify-cms-github-oauth-provider/issues/31

Closing as this is an upstream issue/request.
